// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

console.log("Hello, BuckleScript");

function foo(hasMethodBar) {
  return hasMethodBar.bar();
}

var fakeNames = Belt_Array.map(Belt_Array.range(0, 100), (function (_i) {
        return String(Random.$$int(3000));
      }));

function fakePromise(name) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(name);
                      }), 50);
                
              }));
}

console.log(({
          bar: (function () {
              return "works";
            })
        }).bar());

function $$fetch(url, xmlhttprequest) {
  return xmlhttprequest.request(url, Promise.resolve(undefined));
}

exports.foo = foo;
exports.fakeNames = fakeNames;
exports.fakePromise = fakePromise;
exports.$$fetch = $$fetch;
/*  Not a pure module */
