// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function foo(hasMethodBar) {
  return hasMethodBar.bar();
}

console.log(({
          bar: (function () {
              return "works";
            })
        }).bar());

function foos(string, hasMethodBar) {
  return hasMethodBar.bar(string, undefined);
}

console.log(foos("works2", {
          bar: (function (string, param) {
              return "works" + string;
            })
        }));

exports.foo = foo;
exports.foos = foos;
/*  Not a pure module */
